version: '3.9'

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./local-database:/var/lib/postgresql/data
